### PR TITLE
Made auto configuration Spring Boot 2 compatible

### PR DESCRIPTION
**Pull request by dtrunk90**
Fixes java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

### CODE REVIEW

**Comment by stsundermann** [comment]
:+1: 

Can we have a release once this is merged?

**Comment by ic3fox** [comment]
Hi

This fix will be integrated in the newt release.

Cheers

**Comment by stsundermann** [comment]
When can we expect a new release? This one is holding me and probably many other back from migrating to Spring Boot 2.0

**Comment by dtrunk90** [comment]
As a workaround you can exclude the auto configuration class from jawr (see [here](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/SpringBootApplication.html#exclude--)), copy the configuration class and adapt the import statements to match the refactored spring boot 2 package names.

**Comment by ic3fox** [comment]
Hi dtrunk90,

Thanks for this PR.

Cheers,

**Pull request merged**
